version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: ./containers/api/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
